version: "3.9"
services:
  keycloak-db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
  keycloak:
    image: "quay.io/keycloak/keycloak"
    ports:
      - "8082:8080"
    depends_on:
      - "keycloak-db"
    environment:
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "keycloak-db"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_SCHEMA: "public"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
      - start
      - --proxy edge
      - --hostname-strict=false
      - --hostname-admin-url=https://keycloak-rp.localdomain.com
      - --hostname-url=https://keycloak-rp.localdomain.com
      - --hostname-strict-backchannel=true
