version: "3.9"
services:
  oauth2-proxy:
    image: "quay.io/oauth2-proxy/oauth2-proxy"
    ports:
      - "4180:4180"
    extra_hosts:
      - "keycloak-rp.localdomain.com:172.17.0.1"
      - "rp.localdomain.com:172.17.0.1"
    command:
    - --provider=keycloak-oidc
    - --client-id=POC
    - --client-secret=29w2TKr0mtLMZaOFcuhEG0eH9Hej3oTy
    - --redirect-url=https://rp.localdomain.com/oauth2/callback
    - --oidc-issuer-url=https://keycloak-rp.localdomain.com/realms/POC
    - --cookie-secret=3yVvp2oayAMokKV5-s6uiRPiRlsdCW8_Ig4j4CmlmS0=
    - --cookie-secure=true
    - --reverse-proxy=true
    - --email-domain=*
    - --ssl-insecure-skip-verify=true
    - --ssl-upstream-insecure-skip-verify=true
    - --http-address=0.0.0.0:4180
    - --insecure-oidc-allow-unverified-email=true
    - --show-debug-on-error=true
    - --whitelist-domain=.localdomain.com
    - --pass-access-token=true
    - --pass-authorization-header=true
    - --pass-user-headers=true
    - --set-authorization-header=true
    - --set-xauthrequest=true
    - --cookie-samesite="none"
    - --cookie-httponly="true"
    - --cookie-domain=".localdomain.com"
    - --whitelist-domain=".localdomain.com"
    - --upstream=https://rp.localdomain.com
    - --keycloak-group="allowed_users"
